services:
  tomcat_server:
    build: .
    env_file: ".env"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_db:5432/postgres
    ports:
      - 8081:8080
    command: catalina.sh run
    depends_on:
      - postgres_db
    
  postgres_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 5434:5432


