services:
  tomcat-server:
    build: ./
    command: catalina.sh start
    ports:
      - 8081:8080
    env_file: ".env"
    depends_on:
      - postgres-db
    
  postgres-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 5434:5432


