package org.senla_project.application.service;

import org.senla_project.application.dto.userCollaborationCollabRole.UserCollaborationCollabRoleCreateDto;
import org.senla_project.application.dto.userCollaborationCollabRole.UserCollaborationCollabRoleDeleteDto;
import org.senla_project.application.dto.userCollaborationCollabRole.UserCollaborationCollabRoleResponseDto;
import org.senla_project.application.entity.identifiers.UserCollaborationCollabRoleId;

public interface UserCollaborationCollabRoleService extends CrudService<UserCollaborationCollabRoleCreateDto, UserCollaborationCollabRoleResponseDto, UserCollaborationCollabRoleDeleteDto, UserCollaborationCollabRoleId> {
    void giveUserARoleInCollab(String username, String collabName, String collabRole);
}
